#!/bin/bash

./main tsp_example_1.txt
./main tsp_example_2.txt
./main tsp_example_3.txt
./main test-input-1.txt
./main test-input-2.txt
./main test-input-3.txt
./main test-input-4.txt
./main test-input-5.txt
./main test-input-6.txt
./main test-input-7.txt
